version: '3.7'

services:
  app:
    container_name: se_tz_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: 'postgresql://postgres:password@db:5432/mydatabase'
    depends_on:
      - db
    networks:
      - pg_app

  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_app

volumes:
  postgres_data:

networks:
  pg_app:
    driver: bridge
